version: "3"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: "nestjs_meetup"
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "foo"
      PGADMIN_DEFAULT_PASSWORD: "bar"
    networks:
      - postgres
    ports:
      - "15432:80"
    expose:
      - "5432"
    volumes:
      - pgadmin:/root/.pgadmin
networks:
  postgres:
    driver: bridge
volumes:
  postgres:
  pgadmin:
